//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalorimeterTable1
    {
        public int Id { get; set; }
        public string Table_number { get; set; }
        public Nullable<decimal> Cooling_capacity { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Thermal_power { get; set; }
        public Nullable<decimal> Instantaneous_flow { get; set; }
        public Nullable<decimal> Cumulative_flow { get; set; }
        public Nullable<decimal> Water_supply_temperature { get; set; }
        public Nullable<decimal> Return_watertemperature { get; set; }
        public Nullable<decimal> Cumulative_working_time { get; set; }
        public string Instrument_current_time { get; set; }
        public Nullable<decimal> Instrument_status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual Table_Numbers1 Table_Numbers1 { get; set; }
    }
}
