//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Schedule
    {
        public int id { get; set; }
        public string Table_number { get; set; }
        public Nullable<decimal> Cooling_capacity { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Dosage_Cooling_capacity { get; set; }
        public Nullable<decimal> Dosage_Calories { get; set; }
        public Nullable<decimal> Cost_Cooling_capacity { get; set; }
        public Nullable<decimal> Cost_Calories { get; set; }
        public Nullable<decimal> Total_cost { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> Cooling_price { get; set; }
        public Nullable<decimal> Calories_price { get; set; }
    }
}
