//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Numbers1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Numbers1()
        {
            this.CalorimeterTable1 = new HashSet<CalorimeterTable1>();
            this.User_payment1 = new HashSet<User_payment1>();
        }
    
        public string Table_Number1 { get; set; }
        public int NumberofLayersId { get; set; }
        public string ControlAddress { get; set; }
        public string Port_diection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalorimeterTable1> CalorimeterTable1 { get; set; }
        public virtual NumberofLayers NumberofLayers { get; set; }
        public virtual Table_Numbers1 Table_Numbers11 { get; set; }
        public virtual Table_Numbers1 Table_Numbers12 { get; set; }
        public virtual User_data1 User_data1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_payment1> User_payment1 { get; set; }
    }
}
