//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_pricess
    {
        public int id { get; set; }
        public decimal Calories { get; set; }
        public decimal Cooling_capacity { get; set; }
    }
}
