//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_payment1
    {
        public int id { get; set; }
        public string Table_number { get; set; }
        public string Names { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Billabletime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Table_Numbers1 Table_Numbers1 { get; set; }
    }
}
